"""create inventory_items table

Revision ID: 0f7325a1957d
Revises: 62d38c742be5
Create Date: 2026-05-02 00:28:17.013574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7325a1957d'
down_revision: Union[str, None] = '62d38c742be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('low_stock_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('low_stock_threshold IS NULL OR low_stock_threshold >= 0', name='ck_inventory_threshold_non_negative'),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_category_id'), 'inventory_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_household_id'), 'inventory_items', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_household_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_category_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
