"""create categories table

Revision ID: df366804dce1
Revises: 84a7013e9867
Create Date: 2026-05-01 22:56:05.396650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df366804dce1'
down_revision: Union[str, None] = '84a7013e9867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_type', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'category_type', 'name', name='uq_household_type_name')
    )
    op.create_index(op.f('ix_categories_category_type'), 'categories', ['category_type'], unique=False)
    op.create_index(op.f('ix_categories_household_id'), 'categories', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_household_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_type'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
